# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:

- task: Docker@1
  displayName: Docker build
  inputs:
    dockerFile: Dockerfile
    command: build
    imageName: $(imageName)
    arguments: --target test

- task: Docker@1
  displayName: Docker run
  inputs:
    dockerFile: Dockerfile
    command: run
    imageName: $(imageName)
    containerName: containerWithTestResults
    containerCommand: ls
