# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:

- task: Docker@1
  displayName: Docker build
  inputs:
    azureSubscriptionEndpoint: RMPM (afc11291-9826-46be-b852-70349146ddf8)
    azureContainerRegistry: amazingboseb9e2
    dockerFile: Dockerfile
    command: build
    imageName: $(imageName)

- task: Docker@1
  displayName: Docker push
  inputs:
    azureSubscriptionEndpoint: RMPM (afc11291-9826-46be-b852-70349146ddf8)
    azureContainerRegistry: amazingboseb9e2
    dockerFile: Dockerfile
    command: push
    imageName: $(imageName)
